"""sourcing and email lookups

Revision ID: 29589ce6be0f
Revises: 03650a8ef47d
Create Date: 2026-09-16 15:03:00.080726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29589ce6be0f'
down_revision: Union[str, Sequence[str], None] = '03650a8ef47d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sourcing_cursors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('criteria_hash', sa.String(length=64), nullable=False),
    sa.Column('criteria', sa.JSON(), nullable=False),
    sa.Column('next_page', sa.Integer(), nullable=False),
    sa.Column('exhausted', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('criteria_hash')
    )
    op.create_table('email_lookups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prospect_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('outcome', sa.Enum('found', 'rejected', 'not_found', 'duplicate', 'opted_out', name='emaillookupoutcome', native_enum=False, length=32), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('verification', sa.String(length=32), nullable=True),
    sa.Column('credit_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['prospect_id'], ['prospects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_lookups_created_at'), 'email_lookups', ['created_at'], unique=False)
    op.create_index(op.f('ix_email_lookups_prospect_id'), 'email_lookups', ['prospect_id'], unique=False)
    op.add_column('prospects', sa.Column('email_source', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prospects', 'email_source')
    op.drop_index(op.f('ix_email_lookups_prospect_id'), table_name='email_lookups')
    op.drop_index(op.f('ix_email_lookups_created_at'), table_name='email_lookups')
    op.drop_table('email_lookups')
    op.drop_table('sourcing_cursors')
    # ### end Alembic commands ###
